#!/usr/bin/env node
/**
 * The three places a version is stated must agree.
 *
 * `package.json` is what the repo calls itself, `app.json` is what Expo writes
 * into the built app, and the git tag is what a release is found by. They have
 * drifted before and the drift is silent: the Android project carried 0.1.0
 * while the repo was at 0.3.5, and the device reported 0.1.0 for months because
 * nothing ever compared them.
 *
 * `versionCode` is checked too, and it matters more than it looks. Android
 * compares that integer and ignores the name entirely, so two builds sharing a
 * code are the same build as far as the package manager is concerned. The
 * convention here is major*10000 + minor*100 + patch, which is monotonic and
 * reads back as the version it came from.
 */
import { readFileSync } from 'node:fs';
import { execSync } from 'node:child_process';

const read = (path) => JSON.parse(readFileSync(new URL(`../${path}`, import.meta.url), 'utf8'));

const pkg = read('package.json');
const app = read('app.json').expo;
const problems = [];

if (pkg.version !== app.version) {
  problems.push(`package.json says ${pkg.version}, app.json says ${app.version}`);
}

// The lockfile restates the package version and `npm install` only rewrites
// it when something else changes, so it lagged a whole release (0.5.1 through
// 0.6.0) with nothing comparing it. Harmless to a build, but it is the first
// place a stale checkout is noticed and it should not be allowed to lie.
let lock;
try {
  lock = read('package-lock.json');
} catch {
  lock = undefined;
}
if (lock && lock.version !== pkg.version) {
  problems.push(`package-lock.json says ${lock.version}, package.json says ${pkg.version} (run npm install)`);
}

// `android/` is generated by `expo prebuild` from `app.json`, and Gradle reads
// the version from the generated `build.gradle`, not from `app.json`. Bump the
// version, skip prebuild, run `assembleRelease`, and the APK carries the old
// version while every source of truth agrees with itself. Every build
// installed on 2026-09-13 after the 0.5.0 bump was labelled 0.4.1 that way.
// Absent `android/` is ordinary — it is gitignored — so only a present,
// disagreeing one is a problem.
let gradle;
try {
  gradle = readFileSync(new URL('../android/app/build.gradle', import.meta.url), 'utf8');
} catch {
  gradle = undefined;
}
if (gradle) {
  const gradleName = /versionName\s+"([^"]+)"/.exec(gradle)?.[1];
  const gradleCode = Number(/versionCode\s+(\d+)/.exec(gradle)?.[1]);
  if (gradleName !== app.version || gradleCode !== app.android?.versionCode) {
    problems.push(
      `android/app/build.gradle says ${gradleName ?? 'unset'} (versionCode ${Number.isNaN(gradleCode) ? 'unset' : gradleCode}); ` +
        `run npx expo prebuild --platform android before building`,
    );
  }
}

const match = /^(\d+)\.(\d+)\.(\d+)$/.exec(pkg.version);
if (!match) {
  problems.push(`${pkg.version} is not a bare x.y.z version`);
} else {
  const [, major, minor, patch] = match.map(Number);
  const expected = major * 10000 + minor * 100 + patch;
  if (app.android?.versionCode !== expected) {
    problems.push(`android.versionCode is ${app.android?.versionCode ?? 'unset'}, expected ${expected} for ${pkg.version}`);
  }
}

// Only when this commit is tagged. An untagged commit is ordinary work in
// progress, not a disagreement.
let tag;
try {
  tag = execSync('git describe --tags --exact-match', { stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim();
} catch {
  tag = undefined;
}
if (tag && tag !== pkg.version) {
  problems.push(`this commit is tagged ${tag} but package.json says ${pkg.version}`);
}

// A release must resolve the way a user's install does. On `develop` core is
// consumed through `file:../macha-ts` so this client and core can move in
// parallel, but a tag or `main` carrying that link is a build that works only
// on one machine — and the tagged tree is exactly what ships.
let branch;
try {
  branch = execSync('git branch --show-current', { stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim();
} catch {
  branch = undefined;
}
const releaseContext = tag ? `tagged ${tag}` : branch === 'main' ? 'on main' : undefined;
if (releaseContext) {
  for (const [name, spec] of Object.entries({ ...pkg.dependencies, ...pkg.devDependencies })) {
    if (/^(file|link):/.test(spec)) {
      problems.push(`${releaseContext}, but ${name} is ${spec}; a release must pin a published version`);
    }
  }
}

if (problems.length > 0) {
  console.error('Version mismatch:');
  for (const problem of problems) console.error(`  - ${problem}`);
  process.exit(1);
}

console.log(`${pkg.version} (versionCode ${app.android.versionCode})${tag ? `, tagged ${tag}` : ''} — consistent`);
